### ISSUE TITLE
IllegalReferenceCountException on when using POST method 

### ISSUE THREAD

**Issue by scholzi100** [microbean/microbean-jersey-netty#12]
When sending a request using HTTP POST Method, it results in an `IllegalReferenceCountException`. (logs attached)

Tested using `TestSpike` on version v.0.24.1.
Last working version: v0.12.0

``` 
Suppressed: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
		....
		at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110)
		at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
		at org.microbean.jersey.netty.TerminableByteBufInputStream.close(TerminableByteBufInputStream.java:118)
		at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:135)
		at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:134)
		at org.glassfish.jersey.message.internal.InboundMessageContext$EntityContent.close(InboundMessageContext.java:126)
		at org.glassfish.jersey.message.internal.ReaderWriter.safelyClose(ReaderWriter.java:180)
		at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:907)
		at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:274)
		at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73)
		at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56)
               ....
```
```
$ curl -H "Content-Type:text/plain" -d 'TESTtest' http://localhost:8080/hoopy -v
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /hoopy HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type:text/plain
> Content-Length: 8
> 
* upload completely sent off: 8 out of 8 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server

```

[test.log](https://github.com/microbean/microbean-jersey-netty/files/5583002/test.log)

**Comment by ljnelson** [comment]
Time to stop procrastinating and to write some proper tests! 😄  Could you please run with assertions enabled?  (Maybe they were…but I'd expect various `assert` statements to report this reference problem if so.)

**Comment by scholzi100** [comment]
See #13 for Junit tests

**Comment by scholzi100** [comment]
Enabling assertions does not change anything. No additional throws.

**Comment by ljnelson** [comment]
Thanks.  This is odd.  Notes here are mostly for posterity.

We allocate a new `CompositeByteBuf` here; its reference count is (by definition) 1:

https://github.com/microbean/microbean-jersey-netty/blob/566b426bc07f67c79c4d16ebfca614c653552d5b/src/main/java/org/microbean/jersey/netty/TerminableByteBufInputStream.java#L95

The `CompositeByteBuf` so allocated is only released when the `close()` method is called, and when the state is `CLOSED`:

https://github.com/microbean/microbean-jersey-netty/blob/566b426bc07f67c79c4d16ebfca614c653552d5b/src/main/java/org/microbean/jersey/netty/TerminableByteBufInputStream.java#L116-L119

The only other operation that is performed on the `CompositeByteBuf` (besides `isReadable()` checks) is additive:

https://github.com/microbean/microbean-jersey-netty/blob/566b426bc07f67c79c4d16ebfca614c653552d5b/src/main/java/org/microbean/jersey/netty/TerminableByteBufInputStream.java#L344-L346

(This does not affect the reference count.  The `ByteBuf` that is added as a component has its reference count "transferred" to the `CompositeByteBuf` per Netty's documentation.)

When `release()` is called, which decrements the reference count, the assertion ensures that the reference count being decremented is 1:

https://github.com/microbean/microbean-jersey-netty/blob/566b426bc07f67c79c4d16ebfca614c653552d5b/src/main/java/org/microbean/jersey/netty/TerminableByteBufInputStream.java#L116

Now I need to find out how a reference count of a newly allocated `CompositeByteBuf`, which is by definition 1, goes to 0 when `release()` is not called.

The relevant part of the stack:
```
Suppressed: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
		at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
		at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
		at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
		at io.netty.buffer.CompositeByteBuf$Component.free(CompositeByteBuf.java:1941)
		at io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:2246)
		at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:110)
		at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:100)
		at org.microbean.jersey.netty.TerminableByteBufInputStream.close(TerminableByteBufInputStream.java:118)
```

What's odd here is that ownership of component `ByteBuf`s is supposed to be "transferred" to the `CompositeByteBuf`:

https://netty.io/4.1/api/io/netty/buffer/CompositeByteBuf.html#addComponent-boolean-io.netty.buffer.ByteBuf-

…but this seems to not be happening, maybe?

**Comment by ljnelson** [comment]
I wonder if I need to call `content.retain()` here:

https://github.com/microbean/microbean-jersey-netty/blob/566b426bc07f67c79c4d16ebfca614c653552d5b/src/main/java/org/microbean/jersey/netty/AbstractContainerRequestDecoder.java#L528-L529

…and here:

https://github.com/microbean/microbean-jersey-netty/blob/566b426bc07f67c79c4d16ebfca614c653552d5b/src/main/java/org/microbean/jersey/netty/AbstractContainerRequestDecoder.java#L539

…since `retain()` does not appear to be called anywhere in `CompositeByteBuf`.  Transfer of reference count ownership appears to my naïve eyes to be partial, i.e. yes, `release()` is propagated to the individual components, but nothing prevents them from being released after they've been added to the `CompositeByteBuf`.

**Comment by ljnelson** [comment]
The fixes proposed above do fix the problem.  However, with reference counts one has to be exceptionally careful.  I'm going to see if I can better validate that all components of the `CompositeByteBuf` in question have expected reference counts.

**Comment by ljnelson** [comment]
Thanks @scholzi100 for your help on this one; let me know what the next thing you run into is!
